name: Music

collections:
  songs:
    output: true
    permalink: /:path

theme: jekyll-theme-dinky

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "songs" # a collection in your site, in plural form
    values:
      layout: "song"
